mip_amon = {
    "ta": {
        "frequency": "mon",
        "modeling_realm": "atmos",
        "standard_name": "air_temperature",
        "units": "K",
        "cell_methods": "time: mean",
        "cell_measures": "area: areacella",
        "long_name": "Air Temperature",
        "comment": "Air Temperature",
        "dimensions": "longitude latitude plev19 time",
        "out_name": "ta",
        "type": "real",
        "positive": "",
        "valid_min": "",
        "valid_max": "",
        "ok_min_mean_abs": "",
        "ok_max_mean_abs": "",
    },
    "tas": {
        "frequency": "mon",
        "modeling_realm": "atmos",
        "standard_name": "air_temperature",
        "units": "K",
        "cell_methods": "area: time: mean",
        "cell_measures": "area: areacella",
        "long_name": "Near-Surface Air Temperature",
        "comment": "near-surface (usually, 2 meter) air temperature",
        "dimensions": "longitude latitude time height2m",
        "out_name": "tas",
        "type": "real",
        "positive": "",
        "valid_min": "",
        "valid_max": "",
        "ok_min_mean_abs": "",
        "ok_max_mean_abs": "",
    },
    "pr": {
        "frequency": "mon",
        "modeling_realm": "atmos",
        "standard_name": "precipitation_flux",
        "units": "kg m-2 s-1",
        "cell_methods": "area: time: mean",
        "cell_measures": "area: areacella",
        "long_name": "Precipitation",
        "comment": "includes both liquid and solid phases",
        "dimensions": "longitude latitude time",
        "out_name": "pr",
        "type": "real",
        "positive": "",
        "valid_min": "",
        "valid_max": "",
        "ok_min_mean_abs": "",
        "ok_max_mean_abs": "",
    },
}


coords = {
    "axis_entry": {
        "gridlatitude": {
            "standard_name": "grid_latitude",
            "units": "degrees",
            "axis": "Y",
            "long_name": "Grid Latitude",
            "climatology": "",
            "formula": "",
            "must_have_bounds": "yes",
            "out_name": "rlat",
            "positive": "",
            "requested": "",
            "requested_bounds": "",
            "stored_direction": "increasing",
            "tolerance": "",
            "type": "double",
            "valid_max": "90.0",
            "valid_min": "-90.0",
            "value": "",
            "z_bounds_factors": "",
            "z_factors": "",
            "bounds_values": "",
            "generic_level_name": "",
        },
        "height100m": {
            "standard_name": "height",
            "units": "m",
            "axis": "Z",
            "long_name": "height",
            "climatology": "",
            "formula": "",
            "must_have_bounds": "no",
            "out_name": "height",
            "positive": "up",
            "requested": "",
            "requested_bounds": "",
            "stored_direction": "increasing",
            "tolerance": "",
            "type": "double",
            "valid_max": "120.0",
            "valid_min": "80.0",
            "value": "100.",
            "z_bounds_factors": "",
            "z_factors": "",
            "bounds_values": "",
            "generic_level_name": "",
        },
        "height10m": {
            "standard_name": "height",
            "units": "m",
            "axis": "Z",
            "long_name": "height",
            "climatology": "",
            "formula": "",
            "must_have_bounds": "no",
            "out_name": "height",
            "positive": "up",
            "requested": "",
            "requested_bounds": "",
            "stored_direction": "increasing",
            "tolerance": "",
            "type": "double",
            "valid_max": "30.0",
            "valid_min": "1.0",
            "value": "10.",
            "z_bounds_factors": "",
            "z_factors": "",
            "bounds_values": "",
            "generic_level_name": "",
        },
        "height2m": {
            "standard_name": "height",
            "units": "m",
            "axis": "Z",
            "long_name": "height",
            "climatology": "",
            "formula": "",
            "must_have_bounds": "no",
            "out_name": "height",
            "positive": "up",
            "requested": "",
            "requested_bounds": "",
            "stored_direction": "increasing",
            "tolerance": "",
            "type": "double",
            "valid_max": "10.0",
            "valid_min": "1.0",
            "value": "2.",
            "z_bounds_factors": "",
            "z_factors": "",
            "bounds_values": "",
            "generic_level_name": "",
        },
        "latitude": {
            "standard_name": "latitude",
            "units": "degrees_north",
            "axis": "Y",
            "long_name": "Latitude",
            "climatology": "",
            "formula": "",
            "must_have_bounds": "yes",
            "out_name": "lat",
            "positive": "",
            "requested": "",
            "requested_bounds": "",
            "stored_direction": "increasing",
            "tolerance": "",
            "type": "double",
            "valid_max": "90.0",
            "valid_min": "-90.0",
            "value": "",
            "z_bounds_factors": "",
            "z_factors": "",
            "bounds_values": "",
            "generic_level_name": "",
        },
        "longitude": {
            "standard_name": "longitude",
            "units": "degrees_east",
            "axis": "X",
            "long_name": "Longitude",
            "climatology": "",
            "formula": "",
            "must_have_bounds": "yes",
            "out_name": "lon",
            "positive": "",
            "requested": "",
            "requested_bounds": "",
            "stored_direction": "increasing",
            "tolerance": "",
            "type": "double",
            "valid_max": "360.0",
            "valid_min": "0.0",
            "value": "",
            "z_bounds_factors": "",
            "z_factors": "",
            "bounds_values": "",
            "generic_level_name": "",
        },
        "plev19": {
            "standard_name": "air_pressure",
            "units": "Pa",
            "axis": "Z",
            "long_name": "pressure",
            "climatology": "",
            "formula": "",
            "must_have_bounds": "no",
            "out_name": "plev",
            "positive": "down",
            "requested": [
                "100000.",
                "92500.",
                "85000.",
                "70000.",
                "60000.",
                "50000.",
                "40000.",
                "30000.",
                "25000.",
                "20000.",
                "15000.",
                "10000.",
                "7000.",
                "5000.",
                "3000.",
                "2000.",
                "1000.",
                "500.",
                "100.",
            ],
            "requested_bounds": "",
            "stored_direction": "decreasing",
            "tolerance": "",
            "type": "double",
            "valid_max": "",
            "valid_min": "",
            "value": "",
            "z_bounds_factors": "",
            "z_factors": "",
            "bounds_values": "",
            "generic_level_name": "",
        },
        "time": {
            "standard_name": "time",
            "units": "days since ?",
            "axis": "T",
            "long_name": "time",
            "climatology": "",
            "formula": "",
            "must_have_bounds": "yes",
            "out_name": "time",
            "positive": "",
            "requested": "",
            "requested_bounds": "",
            "stored_direction": "increasing",
            "tolerance": "",
            "type": "double",
            "valid_max": "",
            "valid_min": "",
            "value": "",
            "z_bounds_factors": "",
            "z_factors": "",
            "bounds_values": "",
            "generic_level_name": "",
        },
        "time1": {
            "standard_name": "time",
            "units": "days since ?",
            "axis": "T",
            "long_name": "time",
            "climatology": "",
            "formula": "",
            "must_have_bounds": "no",
            "out_name": "time",
            "positive": "",
            "requested": "",
            "requested_bounds": "",
            "stored_direction": "increasing",
            "tolerance": "",
            "type": "double",
            "valid_max": "",
            "valid_min": "",
            "value": "",
            "z_bounds_factors": "",
            "z_factors": "",
            "bounds_values": "",
            "generic_level_name": "",
        },
    },
}

dataset = {
    "#note_source_type": "explanation of what source_type is goes here",
    "source_type": "AOGCM ISM AER",
    "#note_experiment_id": "CMIP6 valid experiment_ids are found in CMIP6_CV.json",
    "experiment_id": "piControl-withism",
    "activity_id": "ISMIP6",
    "sub_experiment_id": "none",
    "realization_index": "3",
    "initialization_index": "1",
    "physics_index": "1",
    "forcing_index": "1",
    "#note_run_variant": "Text stored in attribute variant_info (recommended, not required description of run variant)",
    "run_variant": "3rd realization",
    "parent_experiment_id": "historical",
    "parent_activity_id": "CMIP",
    "parent_source_id": "PCMDI-test-1-0",
    "parent_variant_label": "r3i1p1f1",
    "parent_time_units": "days since 1850-01-01",
    "branch_method": "standard",
    "branch_time_in_child": 59400.0,
    "branch_time_in_parent": 59400.0,
    "#note_institution_id": "institution_id must be registered at https://github.com/WCRP-CMIP/CMIP6_CVs/issues/new ",
    "institution_id": "PCMDI",
    "#note_source_id": "source_id (model name) must be registered at https://github.com/WCRP-CMIP/CMIP6_CVs/issues/new ",
    "source_id": "PCMDI-test-1-0",
    "calendar": "360_day",
    "grid": "native atmosphere regular grid (3x4 latxlon)",
    "grid_label": "gn",
    "nominal_resolution": "10000 km",
    "license": "CMIP6 model data produced by Lawrence Livermore PCMDI is licensed under a Creative Commons Attribution ShareAlike 4.0 International License (https://creativecommons.org/licenses). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file) and at https:///pcmdi.llnl.gov/. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law.",
    "#output": "Root directory for output (can be either a relative or full path)",
    "outpath": "CMIP6",
    "#note_optional": " **** The following descriptors are optional and may be set to an empty string ",
    "contact ": "Python Coder (coder@a.b.c.com)",
    "history": "Output from archivcl_A1.nce/giccm_03_std_2xCO2_2256.",
    "comment": "",
    "references": "Model described by Koder and Tolkien (J. Geophys. Res., 2001, 576-591).  Also see http://www.GICC.su/giccm/doc/index.html.  The ssp245 simulation is described in Dorkey et al. '(Clim. Dyn., 2003, 323-357.)'",
    "#note_CV": " **** The following will be obtained from the CV and do not need to be defined here",
    "sub_experiment": "none",
    "institution": "",
    "source": "PCMDI-test 1.0 (1989)",
    "#note_CMIP6": " **** The following are set correctly for CMIP6 and should not normally need editing",
    "_controlled_vocabulary_file": "CMIP6_CV.json",
    "_AXIS_ENTRY_FILE": "CMIP6_coordinate.json",
    "_FORMULA_VAR_FILE": "CMIP6_formula_terms.json",
    "_cmip6_option": "CMIP6",
    "mip_era": "CMIP6",
    "parent_mip_era": "CMIP6",
    "tracking_prefix": "hdl:21.14100",
    "_history_template": "%s ;rewrote data to be consistent with <activity_id> for variable <variable_id> found in table <table_id>.",
    "#output_path_template": "Template for output path directory using tables keys or global attributes, these should follow the relevant data reference syntax",
    "output_path_template": "<mip_era><activity_id><institution_id><source_id><experiment_id><_member_id><table><variable_id><grid_label><version>",
    "output_file_template": "<variable_id><table><source_id><experiment_id><_member_id><grid_label>",
}
