name: xcmor
channels:
  - conda-forge
dependencies:
  - python=3
  - netcdf4
  - pip
  - xarray
  - cf_xarray
  - pooch
  - pytest
  - compliance-checker
  - pip:
    - git+https://github.com/larsbuntemeyer/xcmor
