name: xcmor_test
channels:
  - conda-forge
dependencies:
  - pytest-cov
  - pytest
  - pytest-xdist
  - matplotlib-base
  - netcdf4
  - pandas
  - pint
  - pint-xarray
  - pooch
  - rich
  - pooch
  - xarray
  - cf_xarray
  - pip
  - pip:
      - pytest-pretty
